---
abstract: 'blacklist modules you want to prohibit use of'
author:
  - 'Jonas B. Nielsen, (jonasbn) <jonasbn@cpan.org>'
build_requires:
  Test::Perl::Critic: 0
configure_requires:
  Module::Build: 0.40
dynamic_config: 1
generated_by: 'Module::Build version 0.4005, CPAN::Meta::Converter version 2.132830'
license: artistic_2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Perl-Critic-Policy-logicLAB-ModuleBlacklist
provides:
  Perl::Critic::Policy::logicLAB::ModuleBlacklist:
    file: lib/Perl/Critic/Policy/logicLAB/ModuleBlacklist.pm
    version: 0.01
requires:
  Carp: 0
  Data::Dumper: 0
  Perl::Critic::Policy: 0
  Perl::Critic::Utils: 0
  perl: v5.8.0
resources:
  bugtracker: http://rt.cpan.org/NoAuth/Bugs.html?Dist=Perl-Critic-Policy-logicLAB-ModuleBlacklist
  homepage: https://github.com/jonasbn/Perl-Critic-Policy-logicLAB-ModuleBlacklist
  license: http://www.perlfoundation.org/artistic_license_2_0
  repository: https://github.com/jonasbn/Perl-Critic-Policy-logicLAB-ModuleBlacklist
version: 0.01
